<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `chasjr_mystuff`
//

// `chasjr_mystuff`.`BogusNames`
$BogusNames = array(
  array('LineNbr' => '1','Last Name' => 'Meekrazy','First Name' => 'Carl','Gender' => 'M'),
  array('LineNbr' => '2','Last Name' => 'Rigg','First Name' => 'Jerry','Gender' => 'M'),
  array('LineNbr' => '3','Last Name' => 'Staspott','First Name' => 'X. Marx','Gender' => 'FM'),
  array('LineNbr' => '4','Last Name' => 'Body','First Name' => 'Noah','Gender' => 'M'),
  array('LineNbr' => '5','Last Name' => 'Dupp','First Name' => 'Stan','Gender' => 'M'),
  array('LineNbr' => '6','Last Name' => 'Halelujah','First Name' => 'Glory','Gender' => 'F'),
  array('LineNbr' => '7','Last Name' => 'Mentry','First Name' => 'Rudy','Gender' => 'FM'),
  array('LineNbr' => '8','Last Name' => 'Kidding','First Name' => 'R. U.','Gender' => 'FM'),
  array('LineNbr' => '9','Last Name' => 'Svmeenott','First Name' => 'Sheila','Gender' => 'F'),
  array('LineNbr' => '10','Last Name' => 'Bearer','First Name' => 'Paul','Gender' => 'M'),
  array('LineNbr' => '11','Last Name' => 'Zebub','First Name' => 'B. L.','Gender' => 'FM'),
  array('LineNbr' => '12','Last Name' => 'Offalltrades','First Name' => 'Jack','Gender' => 'M'),
  array('LineNbr' => '13','Last Name' => 'Promisses','First Name' => 'M. T.','Gender' => 'FM'),
  array('LineNbr' => '14','Last Name' => 'Sterdnurse','First Name' => 'Reggie','Gender' => 'FM'),
  array('LineNbr' => '15','Last Name' => 'Ghote','First Name' => 'Nannie','Gender' => 'F'),
  array('LineNbr' => '16','Last Name' => 'Francisco','First Name' => 'Sam','Gender' => 'M'),
  array('LineNbr' => '17','Last Name' => 'Krumpits','First Name' => 'T. N.','Gender' => 'FM'),
  array('LineNbr' => '18','Last Name' => 'Meadows','First Name' => 'Dewy','Gender' => 'M'),
  array('LineNbr' => '19','Last Name' => 'Aawn','First Name' => 'Carry','Gender' => 'FM'),
  array('LineNbr' => '20','Last Name' => 'Forcewinds','First Name' => 'Gail','Gender' => 'F'),
  array('LineNbr' => '21','Last Name' => 'Tumaloo','First Name' => 'Skip','Gender' => 'M'),
  array('LineNbr' => '22','Last Name' => 'Canyousee','First Name' => 'Jose','Gender' => 'M'),
  array('LineNbr' => '23','Last Name' => 'Bubb','First Name' => 'Bea L. Z.','Gender' => 'F'),
  array('LineNbr' => '24','Last Name' => 'Redbrehst','First Name' => 'Robin','Gender' => 'FM'),
  array('LineNbr' => '25','Last Name' => 'Meblind','First Name' => 'Rob','Gender' => 'M'),
  array('LineNbr' => '26','Last Name' => 'Sahhutt','First Name' => 'Pete','Gender' => 'M'),
  array('LineNbr' => '27','Last Name' => 'Beatgoazawn','First Name' => 'Anne D.','Gender' => 'F'),
  array('LineNbr' => '28','Last Name' => 'Duewit','First Name' => 'Kenny','Gender' => 'M'),
  array('LineNbr' => '29','Last Name' => 'Wyre','First Name' => 'Barb','Gender' => 'F'),
  array('LineNbr' => '30','Last Name' => 'Tory','First Name' => 'Vick','Gender' => 'M'),
  array('LineNbr' => '31','Last Name' => 'Looyah','First Name' => 'Holly','Gender' => 'F'),
  array('LineNbr' => '32','Last Name' => 'Forapples','First Name' => 'Bob','Gender' => 'M'),
  array('LineNbr' => '33','Last Name' => 'Anndime','First Name' => 'Nick L.','Gender' => 'M'),
  array('LineNbr' => '34','Last Name' => 'Roafone','First Name' => 'Mike','Gender' => 'M'),
  array('LineNbr' => '35','Last Name' => 'Dover','First Name' => 'Ben','Gender' => 'M'),
  array('LineNbr' => '36','Last Name' => 'Ghote','First Name' => 'Billy','Gender' => 'FM'),
  array('LineNbr' => '37','Last Name' => 'Warm','First Name' => 'Luke','Gender' => 'M'),
  array('LineNbr' => '38','Last Name' => 'Monium','First Name' => 'Pam D.','Gender' => 'F'),
  array('LineNbr' => '39','Last Name' => 'Labor','First Name' => 'Manuel','Gender' => 'M'),
  array('LineNbr' => '40','Last Name' => 'Lion','First Name' => 'Dan D.','Gender' => 'M'),
  array('LineNbr' => '41','Last Name' => 'Tee','First Name' => 'Roy L.','Gender' => 'M'),
  array('LineNbr' => '42','Last Name' => 'Ivor','First Name' => 'Herb','Gender' => 'M'),
  array('LineNbr' => '43','Last Name' => 'Duewit','First Name' => 'Wille','Gender' => 'M'),
  array('LineNbr' => '44','Last Name' => 'Klubb','First Name' => 'Billy','Gender' => 'FM'),
  array('LineNbr' => '45','Last Name' => 'Cloth','First Name' => 'Terry','Gender' => 'FM'),
  array('LineNbr' => '46','Last Name' => 'Point','First Name' => 'Sandy','Gender' => 'FM'),
  array('LineNbr' => '47','Last Name' => 'Down','First Name' => 'Sid','Gender' => 'M'),
  array('LineNbr' => '48','Last Name' => 'Di\'Box','First Name' => 'Jack N.','Gender' => 'M'),
  array('LineNbr' => '49','Last Name' => 'Iteverwas','First Name' => 'Sam S.','Gender' => 'M'),
  array('LineNbr' => '50','Last Name' => 'Sharalyke','First Name' => 'Sharon','Gender' => 'F'),
  array('LineNbr' => '51','Last Name' => 'Thatucanbe','First Name' => 'B. Al','Gender' => 'M'),
  array('LineNbr' => '52','Last Name' => 'Meelaider','First Name' => 'Bill','Gender' => 'M'),
  array('LineNbr' => '53','Last Name' => 'Thyme','First Name' => 'Justin','Gender' => 'M'),
  array('LineNbr' => '54','Last Name' => 'Dahskye','First Name' => 'Lucy N.','Gender' => 'F'),
  array('LineNbr' => '55','Last Name' => 'Mighwurd','First Name' => 'Mark','Gender' => 'M'),
  array('LineNbr' => '56','Last Name' => 'Rowthaboatashore','First Name' => 'Micheal','Gender' => 'M'),
  array('LineNbr' => '57','Last Name' => 'Dover','First Name' => 'Eileen','Gender' => 'F'),
  array('LineNbr' => '58','Last Name' => 'Mentry','First Name' => 'Ellie','Gender' => 'F')
);
